name: Hello World

on: 
  workflow_dispatch:

jobs:
  say-hello-1:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
        shell: bash
  say-hello-2:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello using python
        run: print(5 + 5)
        shell: python
  say-hello-3:
    runs-on: ubuntu-latest
    steps:
      - name: IP address
        run: ip a
        shell: bash