name: Secret Test

on:
    workflow_dispatch:

jobs:
    secret-test:
        runs-on: ubuntu-latest
        steps:
            - name: Print Secret
              run: echo "The secret value is: ${{ secrets.PORT }}"
              shell: bash
