name: Secret Test

on:
  workflow_dispatch:

jobs:
  secret-test:
    runs-on: ubuntu-latest 
    steps:
      - name: Print Secret
        run: 'echo "The secret value is: ${{ secrets.PORT }}"'
        shell: bash
      - name: Print Secret in a file
        run: 'echo "The secret value is: ${{ secrets.PORT }}" > secret.txt'
        shell: bash
      - name: Display the content of the file
        run: 'cat secret.txt'
        shell: bash
